### ISSUE TITLE
is there any pretrained model we can download？

### ISSUE THREAD

**Issue by lianuo** [IcewineChen/pytorch-MultiPoseNet#1]
@icewinechen，thanks for yourworks，could you share the weight of entire model for test？

**Comment by IcewineChen** [comment]
Sorry for replying so late. I haven't trained a entire model. Authors of paper share a pretrained model of the final part(pose residual network) , link here: https://github.com/salihkaragoz/pose-residual-network-pytorch, the pretrain branch. Maybe you can use the network and dataloader in this repository to train the model. Thanks for your issue.

**Comment by lianuo** [comment]
@IcewineChen Thank you so much for reply~
